# Configures the canister tests at Travis CI (https://travis-ci.org).

language: golang

go:
 - 1.3

before_install:
 - sudo apt-get install golang
 - git clone https://github.com/bestupefy/canister.git
 - cd canister

script:
 - chmod a+x test
 - ./test
