# Configures the canister tests at Travis CI (https://travis-ci.org).

language: golang

go:
 - 1.3

before_install:
 - sudo apt-get install golang
 - export GOROOT=/usr/local/go
 - export GOPATH=$canister-rkt/go
 - export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
 - git clone https://github.com/bestupefy/canister.git
 - cd canister

script:
 - chmod a+x test
 - ./test
